code --install-extension "Angular.ng-template" --force
code --install-extension "Arjun.swagger-viewer" --force
code --install-extension "bierner.github-markdown-preview" --force
code --install-extension "bierner.markdown-checkbox" --force
code --install-extension "bierner.markdown-emoji" --force
code --install-extension "bierner.markdown-footnotes" --force
code --install-extension "bierner.markdown-mermaid" --force
code --install-extension "bierner.markdown-preview-github-styles" --force
code --install-extension "bierner.markdown-yaml-preamble" --force
code --install-extension "christian-kohler.npm-intellisense" --force
code --install-extension "ckolkman.vscode-postgres" --force
code --install-extension "dbaeumer.vscode-eslint" --force
code --install-extension "dracula-theme.theme-dracula" --force
code --install-extension "eamodio.gitlens" --force
code --install-extension "EditorConfig.EditorConfig" --force
code --install-extension "eriklynd.json-tools" --force
code --install-extension "esbenp.prettier-vscode" --force
code --install-extension "formulahendry.auto-close-tag" --force
code --install-extension "hediet.vscode-drawio" --force
code --install-extension "humao.rest-client" --force
code --install-extension "ms-azuretools.vscode-docker" --force
code --install-extension "ms-edgedevtools.vscode-edge-devtools" --force
code --install-extension "naumovs.color-highlight" --force
code --install-extension "PKief.material-icon-theme" --force
code --install-extension "redhat.java" --force
code --install-extension "redhat.vscode-microprofile" --force
code --install-extension "redhat.vscode-quarkus" --force
code --install-extension "redhat.vscode-yaml" --force
code --install-extension "richie5um2.vscode-sort-json" --force
code --install-extension "runem.lit-plugin" --force
code --install-extension "secanis.jenkinsfile-support" --force
code --install-extension "streetsidesoftware.code-spell-checker" --force
code --install-extension "ue.alphabetical-sorter" --force
code --install-extension "VisualStudioExptTeam.intellicode-api-usage-examples" --force
code --install-extension "VisualStudioExptTeam.vscodeintellicode" --force
code --install-extension "vscjava.vscode-java-debug" --force
code --install-extension "vscjava.vscode-java-dependency" --force
code --install-extension "vscjava.vscode-java-pack" --force
code --install-extension "vscjava.vscode-java-test" --force
code --install-extension "vscjava.vscode-maven" --force
code --install-extension "yzhang.markdown-all-in-one" --force
code --install-extension "orta.vscode-jest" --force
code --install-extension "stylelint.vscode-stylelint" --force
code --install-extension "vivaxy.vscode-conventional-commits" --force
code --install-extension "github.copilot" --force
