# Enable Windows-like alt-tab
cask "alt-tab"
# Menu bar weather app
cask "datweatherdoe"
# Utilities designed to make common development tasks easier
cask "devtoys"
# Utility to hide menu bar items
cask "hiddenbar"
# Clipboard manager
cask "maccy"
# Web browser
cask "microsoft-edge"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# System monitor for the menu bar
cask "stats"
